### ISSUE TITLE
Add 2-3 themes

### ISSUE THREAD

**Issue by amoose** [trevormast/blog-poole#50]
Make choosing sexy

**Comment by trevormast** [comment]
So Simple: http://jekyllthemes.io/theme/10949028/so-simple-theme
Long Haul: http://jekyllthemes.io/theme/27988583/long-haul
Will Jekyll: http://jekyllthemes.io/theme/40167614/will-jekyll-template
Modern Blog: http://jekyllthemes.io/theme/38934900/Jekyll_modern-blog
Grayscale: http://jekyllthemes.io/theme/30191476/grayscale-theme
Compass: http://jekyllthemes.io/theme/28755736/compass
GHub Midnight: http://jekyllthemes.io/theme/3934185/midnight

**Comment by trevormast** [comment]
I think we should choose one template for each of these probable blog uses:  
a Personal Blog
a Professional Blog
a simple site for an Organization

**Comment by amoose** [comment]
Sounds like we need categories on our blog themes. Let's add that to the roadmap.
