### ISSUE TITLE
Make final commits less invasive

### ISSUE THREAD

**Issue by trevormast** [trevormast/blog-poole#73]
Right now we are sequentially committing numbered .txt files every time the GHPages build fails.  This can lead to crowding our users' repos and looks pretty unprofessional.  Let's figure out a better approach:

1) delete extra files after page build

or

2) update existing files for our extra commits

**Comment by trevormast** [comment]
I just realized that deleting the files after the page build would warrant checking the build status again, and could throw us into an infinite loop.  Going to look into updating existing files instead.

**Comment by amoose** [comment]
Completed with #74
